### ISSUE TITLE
query the current municipalities incl cantons

### ISSUE THREAD

**Issue by Rdataflow** [SwissFederalArchives/LD-Tutorials#3]
**use case**
a db would like to fetch the list of current municipalities incl the cantons they belong to.

**proposed query**
https://s.zazuko.com/mdAQxr

@bequrios can you insert this query somewhere to make it accessible to others?

nb: reviewed by @l00mi

**Comment by bequrios** [comment]
thanks for the proposal, added part 3.2.11 with slightly different query strategy in https://github.com/SwissFederalArchives/LD-Tutorials/commit/3a7f630ac17f0868c7918c22b814debba11a95f6
